apiVersion: batch/v1
kind: Job
metadata:
  name: ${cockroachdbcluster.name}-cluster-init
  labels:
    app: ${cockroachdbcluster.name}
spec:
  template:
    spec:
      containers:
      - name: cluster-init
        image: cockroachdb/cockroach:v19.2.2
        imagePullPolicy: IfNotPresent
        command:
          - "/cockroach/cockroach"
          - "init"
          - "--insecure"
          - "--host=${cockroachdbcluster.name}-0.${cockroachdbcluster.name}"
      restartPolicy: OnFailure
