apiVersion: v1
kind: Namespace
metadata:
  name: simple-cockroachdb-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-cockroachdb-operator
  namespace: simple-cockroachdb-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple-cockroachdb-operator
rules:
# -------------------------------------------------------------------------
# The custom resource definition (CRD) is created by the operator.
# It needs to create, list, watch, get CRDs.
# -------------------------------------------------------------------------
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create"]
# -------------------------------------------------------------------------
# For the custom resource, the operator needs list, watch, get.
# -------------------------------------------------------------------------
- apiGroups: ["io.marlonpatrick"]
  resources: ["cockroachdbclusters"]
  verbs: ["get", "list", "watch"]
# -------------------------------------------------------------------------
# The following are the resources created by the operator,
# the operator needs to list, watch, get,create, update and delete these resources.
# -------------------------------------------------------------------------
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simple-cockroachdb-operator
roleRef:
  kind: ClusterRole
  name: simple-cockroachdb-operator
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: simple-cockroachdb-operator
    namespace: simple-cockroachdb-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-cockroachdb-operator
  namespace: simple-cockroachdb-operator
  labels: &default-labels
    app.kubernetes.io/name: simple-cockroachdb-operator
    app.kubernetes.io/version: v0.0.1-v1alpha1
spec:
  replicas: 1
  selector:
    matchLabels: *default-labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *default-labels
    spec:
      serviceAccountName: simple-cockroachdb-operator
      containers:
      - name: simple-cockroachdb-operator
        image: quay.io/marlonpatrick/simple-cockroachdb-operator:latest
        env:
        #- name: WATCHED_NAMESPACE # if not specified all the namespaces will be watched; ~ denotes the same ns as the operator's
        #  value: myproject
        #- name: COLORS
        #  value: false
        - name: FULL_RECONCILIATION_INTERVAL_S
          value: "180"
        imagePullPolicy: Always